name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download JsonRpcNet.Docs.Ui
      uses: fabriciobastian/download-release-asset-action@v1.0.2
      with:
        version: latest
        repository: JsonRpcNet/JsonRpcNet.Docs.Ui
        file: jsonrpcnet-docs-ui.zip
    - name: Unzip JsonRpcNet.Docs.Ui and move it into project
      run: |
        unzip jsonrpcnet-docs-ui.zip
        rm -v jsonrpcnet-docs-ui.zip
        mv -v ./dist ./src/JsonRpcNet.Core/web
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build src/JsonRpcNet.Core.sln --configuration Release
